export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "HIDE_ALERT";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const CURRENT_USER_BEGIN = "CURRENT_USER_BEGIN";

export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";

export const ALL_USERS_BEGIN = "ALL_USERS_BEGIN";

export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";

export const ALL_USERS_ERROR = "ALL_USERS_ERROR";
